### ISSUE TITLE
[Feedback] Documentation on Kubernetes

### ISSUE THREAD

**Issue by bodak** [acouvreur/sablier#121]
I successfully set this up in a K3S, Traefik 2.0, localized plugin (no hub integration) and IngressRoute stack. I mainly followed the [code-server guide](https://github.com/acouvreur/sablier/blob/main/docs/guides/code-server-traefik-kubernetes.md).

### Feedback points:
- Under 5.5 where you create the middleware, it wasn't clear until I looked at your main README.md how you specify `names`. https://github.com/acouvreur/sablier/blob/main/plugins/traefik/README.md#traefik-with-kubernetes.

Initially, I had it just as the deployment name i.e. `code-server-deployment`. Interestingly, this resulted in the sablier deployment crashing with:
```
time="2022-12-02T10:04:48Z" level=info msg="(version=1.2.0, branch=HEAD, revision=3176848116340590d702f0170a51c517696f7629)"
time="2022-12-02T10:04:48Z" level=info msg="using provider \"kubernetes\""
time="2022-12-02T10:04:48Z" level=info msg="initialized storage to /etc/sablier/state.json"
time="2022-12-02T10:04:48Z" level=info msg="server listening :10000"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1081364]

goroutine 86 [running]:
github.com/acouvreur/sablier/app/providers.(*KubernetesProvider).Start(0x400057003a?, {0x400057003a, 0x7})
	/go/src/sablier/app/providers/kubernetes.go:80 +0x64
github.com/acouvreur/sablier/app/sessions.(*SessionsManager).requestSessionInstance(0x400011e800, {0x400057003a, 0x7}, 0x0?)
	/go/src/sablier/app/sessions/sessions_manager.go:146 +0x44c
github.com/acouvreur/sablier/app/sessions.(*SessionsManager).RequestSession.func1({0x400057003a, 0x7})
	/go/src/sablier/app/sessions/sessions_manager.go:125 +0x74
created by github.com/acouvreur/sablier/app/sessions.(*SessionsManager).RequestSession
	/go/src/sablier/app/sessions/sessions_manager.go:123 +0xd4
```
- I can confirm sablier also works with Traefik's IngressRoute CRD provider https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/
  It requires you change the below during your helm install/upgrade.
  `values.yaml`:
```
  providers:
    kubernetesCRD:
      enabled: true
      allowEmptyServices: true
```
  IngressRoute example for code-server
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: code-server-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`localhost`) && PathPrefix(`/`)
    middlewares:
      - name: code-server-sablier
    services:
    - name: code-server-service
      port: 8080
      namespace: default
```
- Finally, I prefer to install your plugin locally and disable Traefik hub integration. To achieve this you need to add the following to your `values.yaml`
```
hub:
  enabled: false
deployment:
  initContainers:
    - name: traefik-plugins
      image: k8s.gcr.io/git-sync/git-sync:v3.6.2
      args: ["-v", "6"]
      volumeMounts:
        - name: traefik
          mountPath: /plugins-local
      env:
        - name: GIT_SYNC_REPO
          value: https://github.com/acouvreur/sablier
        - name: GIT_SYNC_REV  # to 1.2.0
          value: "3176848116340590d702f0170a51c517696f7629"
        - name: GIT_SYNC_ROOT
          value: /plugins-local/src/github.com/acouvreur/
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_DEPTH
          value: "1"
        - name: GIT_SYNC_LINK
          value: sablier
        - name: GIT_SYNC_PERMISSIONS
          value: "0777"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
 additionalArguments:
    - "--experimental.localplugins.sablier.modulename=github.com/acouvreur/sablier"
persistence:
  enabled: true
  name: traefik
  accessMode: ReadWriteOnce
  size: 128Mi
  storageClass: ""
  path: /plugins-local
  annotations: {}
```
