### ISSUE TITLE
Kubernetes provider with blocking strategy fails first request

### ISSUE THREAD

**Issue by abatilo** [acouvreur/sablier#131]
**Describe the bug**
If I set my traefik middleware to use sablier with the blocking strategy, then the first request to my application returns a 503 because traefik doesn't see any available endpoints for the application.

**Context**
 - Sablier version: 1.2.0
 - Provider: Kubernetes
 - Reverse proxy: traefik v2.8.5

**Expected behavior**
I expect sablier to wait until my pods are actually ready before moving on and trying to forward requests to the downstream containers.

**Additional context**
Here's what my middleware definition looks like.
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: friendlyfaces-sablier-blocking
spec:
  plugin:
    sablier:
      names: deployment_default_friendlyfaces_1
      sablierUrl: 'http://sablier.kube-system:10000'
      sessionDuration: 15m
      blocking:
        default-timeout: 1m
```
