### ISSUE TITLE
Support multiple docker sockets/proxy

### ISSUE THREAD

**Issue by vutsalsinghal** [acouvreur/sablier#162]
Hi,

Love `sablier`! 

I believe this is not super unusual to have multiple docker connections. For example - For example, I've three currently:

```
machine1:
  socket: /var/run/docker.sock

machine2:
  host: 192.168.0.81
  port: 10001

machine3:
  host: 192.168.0.81
  port: 10002
``` 

So basically in the subrequest to sablier backend from nginx (or traefik), when using docker provider, it should also pass something like `sablierServer` which can then be used to start/stop/query container status. 

Homepage project ([link](https://gethomepage.dev/en/configs/docker/#using-docker-socket-proxy)) uses this concept to display the status and container stats.
