### ISSUE TITLE
Dynamic status page not showing via Traefik

### ISSUE THREAD

**Issue by dimber-cais** [acouvreur/sablier#165]
**Describe the bug**
When a group is scaling up and dynamic strategy is used, I expect to see the themed loading page. Instead I just see a pending request from the browser (so blank page).

**Context**
 - Sablier version: ghcr.io/acouvreur/sablier:beta
 - Provider: kubernetes 1.24
 - Reverse proxy: Traefik 2.9
 - Sablier running inside a container? Yes

**Expected behavior**
When using the following middleware:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: sablier
spec:
  plugin:
    sablier:
      group: test
      sablierUrl: 'http://sablier.sablier.svc.cluster.local:10000'
      sessionDuration: 30s
      dynamic:
        displayName: 'test'
        showDetails: true
        theme: hacker-terminal
        refreshFrequency: 5s
```
I would expect to see the loading page until pods are ready. However, the request does not complete and remains pending. 

**Additional context**
* Interestingly, if I `port-forward` to the `sablier` pod, and I issue a request to `http://localhost:10000/api/strategies/dynamic?group=test` I do see the page.
* Aside from the loading page not showing up, the scaling up and down is working correctly.

**Comment by dimber-cais** [comment]
Looking at the docs here: https://acouvreur.github.io/sablier/#/guides/code-server-traefik-kubernetes

It shows using Traefik plugin version `v1.4.0-beta.4` but this doesn't appear to be published [here](https://plugins.traefik.io/plugins/633b4658a4caa9ddeffda119/sablier). The latest is `v1.4.0-beta.3`.

Also it shows using docker container `acouvreur/sablier:1.4.0-beta.4` which also does not exist.

**Comment by acouvreur** [comment]
> Looking at the docs here: https://acouvreur.github.io/sablier/#/guides/code-server-traefik-kubernetes
> 
> It shows using Traefik plugin version `v1.4.0-beta.4` but this doesn't appear to be published [here](https://plugins.traefik.io/plugins/633b4658a4caa9ddeffda119/sablier). The latest is `v1.4.0-beta.3`.
> 
> Also it shows using docker container `acouvreur/sablier:1.4.0-beta.4` which also does not exist.

Yes, you're right about that. The last action did not trigger the releases on tagging, I have to fix that by force publishing myself, I will do it soon.

**Comment by acouvreur** [comment]
> **Describe the bug** When a group is scaling up and dynamic strategy is used, I expect to see the themed loading page. Instead I just see a pending request from the browser (so blank page).
> 
> **Context**
> 
> * Sablier version: ghcr.io/acouvreur/sablier:beta
> * Provider: kubernetes 1.24
> * Reverse proxy: Traefik 2.9
> * Sablier running inside a container? Yes
> 
> **Expected behavior** When using the following middleware:
> 
> ```yaml
> apiVersion: traefik.containo.us/v1alpha1
> kind: Middleware
> metadata:
>   name: sablier
> spec:
>   plugin:
>     sablier:
>       group: test
>       sablierUrl: 'http://sablier.sablier.svc.cluster.local:10000'
>       sessionDuration: 30s
>       dynamic:
>         displayName: 'test'
>         showDetails: true
>         theme: hacker-terminal
>         refreshFrequency: 5s
> ```
> 
> I would expect to see the loading page until pods are ready. However, the request does not complete and remains pending.
> 
> **Additional context**
> 
> * Interestingly, if I `port-forward` to the `sablier` pod, and I issue a request to `http://localhost:10000/api/strategies/dynamic?group=test` I do see the page.
> * Aside from the loading page not showing up, the scaling up and down is working correctly.

For your issue here, I'd be curious about your Traefik setup, can you please share more of the Traefik setup itself? With Sablier, the service you try to setup for scale to zero and Traefik itself? Thanks

**Comment by dimber-cais** [comment]
Hi,

Here's the Traefik config:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: sablier
  namespace: test
spec:
  plugin:
    sablier:
      group: test
      sablierUrl: 'http://sablier.sablier.svc.cluster.local:10000'
      sessionDuration: 30s
      dynamic:
        displayName: 'test'
        showDetails: true
        theme: hacker-terminal
        refreshFrequency: 5s
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: test
    namespace: test
spec:
    entryPoints:
        - https-external
    tls:
        secretName: external-tls
    routes:
        -   kind: Rule
            match: Host(`test.test.com`) && PathPrefix(`/test/v1`)
            middlewares:
              - name: sablier
                namespace: test
            services:
                -   kind: Service
                    name: test
                    namespace: test
                    port: 8080
```

There's nothing special about the deployment except that it initially starts out with zero replicas and has the sablier labels added
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
  labels:
    app: test
    sablier.enable: "true"
    sablier.group: "test"
spec:
  replicas: 0
```

As you can see we utilize the Traefik `IngressRoute` CRD rather than the standard K8 `Ingress` resource. Our static configuration looks like this:

```yaml
...
providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowEmptyServices: true
experimental:
  plugins:
    sablier:
      moduleName: "github.com/acouvreur/sablier"
      version: "v1.4.0-beta.3"
```

**Comment by dimber-cais** [comment]
This is the static configuration
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sablier-config
data:
  sablier.yaml: |
    provider:
      # Provider to use to manage containers (docker, swarm, kubernetes)
      name: kubernetes
    server:
      # The server port to use
      port: 10000
      # The base path for the API
      base-path: /
    storage:
      # File path to save the state (default stateless)
      file:
    sessions:
      # The default session duration (default 5m)
      default-duration: 15m
      # The expiration checking interval.
      # Higher duration gives less stress on CPU.
      # If you only use sessions of 1h, setting this to 5m is a good trade-off.
      expiration-interval: 60s
    logging:
      level: debug
    strategy:
      dynamic:
        # Custom themes folder, will load all .html files recursively (default empty)
        custom-themes-path:
        # Show instances details by default in waiting UI
        show-details-by-default: true
        # Default theme used for dynamic strategy (default "hacker-terminal")
        default-theme: hacker-terminal
        # Default refresh frequency in the HTML page for dynamic strategy
        default-refresh-frequency: 10s
      blocking:
        # Default timeout used for blocking strategy (default 1m)
        default-timeout: 5m
```

**Comment by acouvreur** [comment]
```yaml
        - name: sablier
          image: acouvreur/sablier:1.3.0
          args:
            - "start"
            - "--configFile=/sablier.yaml"  
```

Here you are using version 1.3.0 which does not yet support groups, can you use the beta tag instead and try it out?
