### ISSUE TITLE
Guidance on Traefik and multiple groups

### ISSUE THREAD

**Issue by deimosfr** [acouvreur/sablier#177]
**Describe the bug**
Hi, first thanks a lot for your work! I don't get how to use multiple groups with Traefik.

**Context**
 - Sablier version: v1.4.0-beta.5
 - Provider: docker v20.10.23
 - Reverse proxy: traefik v2.10.4
 - Sablier running inside a container: yes

**Expected behavior**
I've followed documentations:
* https://github.com/acouvreur/sablier/tree/main/plugins/traefik#traefik-with-docker-classic
* https://acouvreur.github.io/sablier/#/plugins/traefik

Unfortunately, there are no examples of Traefik working with multiple groups. So basically, here is a config with two containers. If they both belong to the default group, then it will work:

```yaml
  grafana:
    image: grafana/grafana:10.0.5
    container_name: grafana
    restart: "no"
    ports:
      - "3000:3000"
    labels:
      sablier.enable: true
      sablier.group: default

  flame:
    image: pawelmalak/flame:2.3.1
    container_name: flame
    restart: "no"
    labels:
      sablier.enable: true
      sablier.group: default
    ports:
      - "5005:5005"
```

And my configuration inside Traefik:
```yaml
  middlewares:
    sablier:
      plugin:
        sablier:
          dynamic:
            refreshFrequency: 5s
            showDetails: "true"
            theme: shuffle
          group: default
          sablierUrl: http://127.0.0.1:10000
          sessionDuration: 1m
```

How should I declare multiple groups? From a YAML POV, there are no list, so no way to perform multiple group configs.

If I try to update the group name of one of the 2 declared containers above, then it will not shutdown anymore. And I don't want those to be part of the same group (so waking up one service, will wake up others), because it's 2 different services.

Thanks in advance
