### ISSUE TITLE
panic: unimplemented provider docker_swarm

### ISSUE THREAD

**Issue by afuca** [acouvreur/sablier#210]
**Describe the bug**
I'm trying to use sablier in a container on a swarm. And I get the following error in docker logs after deploy command.

```
time="2023-10-04T09:25:51Z" level=info msg="(version=1.4.0, branch=HEAD, revision=a39d35e1274f04468838e686499e37196a821062)"
panic: unimplemented provider docker_swarm

goroutine 1 [running]:
github.com/acouvreur/sablier/cmd.glob..func2.1(0xc0000c2f00?, {0x1b3919f?, 0x4?, 0x1b391a3?})
	/go/src/sablier/cmd/start.go:18 +0x73
github.com/spf13/cobra.(*Command).execute(0xc000324900, {0xc0003b4e80, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc000324600)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/acouvreur/sablier/cmd.Execute()
	/go/src/sablier/cmd/root.go:26 +0x18
main.main()
	/go/src/sablier/main.go:10 +0x69
```

**Context**
 - Sablier version: 1.4.0
 - Provider: docker_swarm
 - Reverse proxy: traefik:v2.10
 - Sablier running inside a container? Yes

**Expected behavior**
Sablier container starting.

**Additional context**
The compose configuration for sablier : 
```yml
services:
  sablier:
    image: acouvreur/sablier:1.4
    command:
      - start
      - --provider.name=docker_swarm
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
```

I also tried with beta and latest image. Same results.
