### ISSUE TITLE
Detection for manually stop/start services and resetting spin-down timer

### ISSUE THREAD

**Issue by foureight84** [acouvreur/sablier#25]
I have a service that is set to spin down after 10 minutes and I've noticed that if I take the service offline and back online during that time frame via docker stack rm and deploy, I won't be able to access the service until the spin-down timer has been reached. I am currently running this plugin in local mode instead of using Pilot (not sure if this issue applies if deployed using Pilot).

Is there a way to manually reset the spin-down timer?

**Comment by acouvreur** [comment]
Can you describe your Traefik confiuration and how the routing is done ?

If this is done using `labels`, then the routing is destroyed with the `docker stack rm` command.

Wether you bring the service up or not, the ondemand service will emit a scale down request.

So one weird behavior is in fact recreating the same stack/service while it is scaled down. Creating the stack **manually** sets the number of replicas to 1.
While you do not access the service, it will be scaled down.

**Comment by foureight84** [comment]
Here are my current docker stacks:

`management stack`
```

version: "3.7"

services:
  traefik:
    image: traefik:latest
    ports:
      - target: 53
        published: 53
        protocol: tcp
      - target: 53
        published: 53
        protocol: udp
      - target: 80
        published: 80
        protocol: tcp
    environment:
      - TZ=US/Los_Angeles
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - './plugins-local:/plugins-local/'
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=Host(`traefik.hades.home`)
        - traefik.http.routers.api.service=api@internal
        - traefik.http.routers.api.entrypoints=web
        - traefik.http.services.api.loadbalancer.server.port=8080
  
  ondemand:
    image: ghcr.io/acouvreur/traefik-ondemand-service:1.7
    command:
      - --swarmMode=true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - traefik

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik
    deploy:
      labels:
        # WebUI
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host(`portainer.hades.home`)
        - traefik.http.routers.portainer.entrypoints=web
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        - traefik.http.routers.portainer.service=portainer

networks:
  traefik:
    external: true


volumes:
  portainer_data:

```

Here is my `monitoring` stack:

```

version: "3.7"

services:
  glances:
    image: nicolargo/glances:latest-alpine
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "GLANCES_OPT=-w"
    networks:
      - traefik
    deploy:
      replicas: 0
      labels:
        - traefik.enable=true
        - traefik.http.routers.glances.rule=Host(`glances.hades.home`)
        - traefik.http.routers.glances.entrypoints=web
        - traefik.http.services.glances.loadbalancer.server.port=61208
        - traefik.docker.lbswarm=true
        - traefik.http.middlewares.ondemand_glances.plugin.traefik-ondemand-plugin.name=monitoring_glances
        - traefik.http.middlewares.ondemand_glances.plugin.traefik-ondemand-plugin.serviceurl=http://ondemand:10000
        - traefik.http.middlewares.ondemand_glances.plugin.traefik-ondemand-plugin.timeout=10m
        - traefik.http.routers.glances.middlewares=ondemand_glances@docker
        
networks:
  traefik:
    external: yes

```

As you mentioned, the routing gets destroyed from Traefik after `docker stack rm monitoring` and the spin-down timer will trigger after 10 minutes. However, testing that again but instead of waiting for the timer to spin down, I bring the monitoring stack back up with `docker stack deploy` and watch traefik for the routes to get detected. Once the routes are detected, I browse to `glances.hades.home` and I receive a 502 'Bad Gateway' response.

For the route to work again, I will need to wait until the spin-down has elapsed starting from the timestamp of the last connection attempt.

This is the error log observed from Traefik:

```

time="2022-04-22T02:15:34Z" level=error msg="2022/04/22 02:15:34 Status: started" plugin=plugin-traefik-ondemand-plugin module=github.com/acouvreur/traefik-ondemand-plugin
time="2022-04-22T02:15:34Z" level=error msg="2022/04/22 02:15:34 Sending request: http://ondemand:10000?name=monitoring_glances&timeout=10m0s" module=github.com/acouvreur/traefik-ondemand-plugin plugin=plugin-traefik-ondemand-plugin
time="2022-04-22T02:13:50Z" level=error msg="2022/04/22 02:13:50 Status: started" plugin=plugin-traefik-ondemand-plugin module=github.com/acouvreur/traefik-ondemand-plugin
time="2022-04-22T02:13:50Z" level=error msg="2022/04/22 02:13:50 Sending request: http://ondemand:10000?name=monitoring_glances&timeout=10m0s" module=github.com/acouvreur/traefik-ondemand-plugin plugin=plugin-traefik-ondemand-plugin
time="2022-04-22T02:04:22Z" level=error msg="2022/04/22 02:04:22 Status: started" plugin=plugin-traefik-ondemand-plugin module=github.com/acouvreur/traefik-ondemand-plugin
time="2022-04-22T02:04:22Z" level=error msg="2022/04/22 02:04:22 Sending request: http://ondemand:10000?name=monitoring_glances&timeout=10m0s" plugin=plugin-traefik-ondemand-plugin module=github.com/acouvreur/traefik-ondemand-plugin
time="2022-04-22T02:04:02Z" level=error msg="2022/04/22 02:04:02 Status: started" plugin=plugin-traefik-ondemand-plugin module=github.com/acouvreur/traefik-ondemand-plugin
time="2022-04-22T02:04:02Z" level=error msg="2022/04/22 02:04:02 Sending request: http://ondemand:10000?name=monitoring_glances&timeout=10m0s" plugin=plugin-traefik-ondemand-plugin module=github.com/acouvreur/traefik-ondemand-plugin

```
