### ISSUE TITLE
Blank pages when sablier attempts to redirect to application page

### ISSUE THREAD

**Issue by accforgithubtest** [acouvreur/sablier#264]
I have gotten Sablier to work with Caddy (caddy-docker-proxy) and have it set up for a few applications (homer, dozzle, filebrowser, code-server). All applications are using the latest versions as of today, using docker compose (non-swarm).

I notice a weird issue with the below sequence of steps -
1. When I open the application url in the browser (homer.local.host or filebrowser.local.host, etc), I see the sablier intermediate loading page (using shuffle theme).
2. I can see the docker container is started up and the logs in the application containers as well as caddy and sablier containers are all looking fine - no errors.
3. Sablier has recognized that the container is running (no health checks configured). 
4. At this point sablier attempts to navigate from the intermediate loading page (shuffle themed) to the application page.
5. I see a blank page. Pressing just f5 doesn't help, still see only the blank page. Pressing ctrl+f5 takes me to the application page.
6. Checked all the application container logs as well as caddy and sablier container logs - no errors.

I see this issue in firefox incognito window. I am able to recreate this issue consistently every single time.
I tried the same in chrome browser (normal window / non-incognito) and the issue is seen sometimes, however not seen at other times.
In both browsers, pressing ctrl+f5 open the application window. Its only the intermediate blank page that is the issue.

Pls let me know if any additional information can help to check this issue.

**Comment by acouvreur** [comment]
Hello! Can you provide more details on your configuration ?

Such as the configuration itself from caddy ?

**Comment by accforgithubtest** [comment]
Here is an example file I have prepared from my actual files.

```yaml
services:
  caddy:
    image: serfriz/caddy-ratelimit-dockerproxy-sablier:latest
    container_name: caddy
    dns: 10.0.0.25 #pihole
    restart: always
    environment:
      - CADDY_INGRESS_NETWORKS=test_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - path/to/self-signed certificate files:/certs:ro
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 10000:10000
    labels:
      caddy.order: sablier before reverse_proxy
    networks:
      default:
          ipv4_address: 10.0.0.26

  homer:
    image: b4bz/homer:latest
    container_name: homer
    dns: 10.0.0.25 #pihole
    restart: always
    environment:
      - INIT_ASSETS=0
    volumes:
      - ./:/www/assets
    ports:
      - 8080
    labels:
      caddy: homer.local.host
      caddy.tls: "path to self-signed certificate files"
      caddy.sablier.enable: true
      caddy.sablier.names: homer
      caddy.sablier.dynamic:
    networks:
      default:
          ipv4_address: 10.0.0.27
```
