### ISSUE TITLE
Caddyfile parse error: first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by valankar** [acouvreur/sablier#291]
**Describe the bug**
Error using Caddy with provided config.

```
        route /accounts_plotly {
                sablier url=http://localhost:10000 {
                        group accounts
                        session_duration 1m
                        dynamic {
                                display_name Accounts
                        }
                }
                reverse_proxy localhost:8050
        }
```

```
Error: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 6: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 9: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'sablier': provision http.handlers.sablier: parse "url=http://localhost:10000/api/strategies/dynamic": first path segment in URL cannot contain colon
```

My compose file:
```
  sablier:
    image: acouvreur/sablier
    container_name: sablier
    network_mode: host
    command:
        - start
        - --provider.name=docker
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
```

My Dockerfile:

```
FROM caddy:builder AS builder

ADD https://github.com/acouvreur/sablier.git /sablier

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/lanrat/caddy-dynamic-remoteip \
    --with github.com/WeidiDeng/caddy-cloudflare-ip \
    --with github.com/acouvreur/sablier/plugins/caddy=/sablier/plugins/caddy

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Context**
 - Sablier version: Latest version. I did not specify one.
 - Provider: docker 26.1.0
 - Reverse proxy: caddy latest
 - Sablier running inside a container? Yes.

**Expected behavior**
I think I'm specifying the config right, but maybe I'm missing something?
