### ISSUE TITLE
Showing error page instead of loading page

### ISSUE THREAD

**Issue by Sblop** [acouvreur/sablier#35]
Hi Acouvreur,

Great service. Love the plugin and the service. I do however have a problem, that the plugin loads the error page every time, instead of the loading page. 
Setup. I start all my services using a .sh script, calling docker compose files. Therefore using docker classic...

Error:
```
Error loading Who am I.

There was an error loading your instance.
Get "http://ondemand:10000?name=who&timeout=1m0s": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
The service does seem to respond correctly:
```
09/23/2022 8:37:11 AM
time="2022-09-23T08:37:11+02:00" level=info msg="Scaling up who to 1"
09/23/2022 8:38:27 AM
time="2022-09-23T08:38:27+02:00" level=info msg="Scaling down who to 0"
```
Below snippets from dynamic-conf in Traefik. (http/services/middlewares are missing. This is only snippets of the specific conf.)
```
    chain-who:
      chain:
        middlewares:
          - odm-who
          - chain-default

    odm-who:
      plugin:
        traefik-ondemand-plugin:
          serviceUrl: http://ondemand:10000
          name: who
          displayname: "Who am I"
          timeout: 1m
          waitui: true

    who:
      loadBalancer:
        servers:
        - url: "http://who:80"

    who:
      rule: Host("who.domain.tld")
      entryPoints:
        - "websecure"
      middlewares:
        - chain-who
      service: "who"
      tls: true

```
I have tried adding below to  my static conf.
```
      - "--serversTransport.forwardingTimeouts.dialTimeout=30s"
      - "--serversTransport.forwardingTimeouts.idleConnTimeout=30s"
```
But this didnt make any difference. Do you have any idea what might be causing the client time-out? All my trafik is sent through cloudflare argo tunnels, but this seems to be happening only server-side?
