### ISSUE TITLE
code-server on demand isn't working as expected

### ISSUE THREAD

**Issue by edoardo-conti** [acouvreur/sablier#37]
Hello,

Great plugin but I have a problem, the vscode server does not keep the container active, let me explain better.

The plugin always stops the container after exactly 1 minute from the startup even if I am writing code and if this happens (code-server shutting down while I'm using it) it doesn't come back up if i try to reach it via url with traefik host rule. 
Is this supposed to happen? Can the plugin work as I'm expecting with vscode? 

docker-compose.yml :
```
version: "3.3"

services:
  traefik:
    image: "traefik:latest"
    container_name: traefik
    command:
      - --api=true
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker
      # plugin: ondemand
      - --experimental.plugins.traefik-ondemand-plugin.moduleName=github.com/acouvreur/traefik-ondemand-plugin
      - --experimental.plugins.traefik-ondemand-plugin.version=v1.2.0
      - --providers.file.filename=/etc/traefik/dynamic-config.yml
      - --log.level=ERROR
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik_local
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/root/dynamic-config.yml:/etc/traefik/dynamic-config.yml"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    networks:
      - traefik_local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.fritz.box`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.fritz.box`)"
      - "traefik.http.routers.edge.entrypoints=web"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"

  ondemand:
    image: ghcr.io/acouvreur/traefik-ondemand-service:latest
    container_name: ondemand
    command: 
      - --swarmMode=false
    networks:
      - traefik_local
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ondemand.name=ondemand"
      - "traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.name=code-server"
      - "traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.serviceUrl=http://ondemand:10000"
      - "traefik.http.middlewares.ondemand.plugin.traefik-ondemand-plugin.timeout=1m"
      - "traefik.http.services.ondemand.loadbalancer.server.port=10000"

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Rome
    ports:
      - 8443:8443
    networks:
      - traefik_local
    volumes:
      - /root/containers/codeserver/config:/config
      - /root:/photonos_vm/root/
    restart: on-failure
    labels:
      # vscode
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.name=code-server"

networks:
  traefik_local:
    name: traefik_local

volumes:
  portainer_data:
    name: portainer_data
```

dynamic-config.yml :
```
http:
  services:
    code-server:
      loadBalancer:
        servers:
        - url: "http://code-server:8443"
  routers:
    code-server:
      rule: Host(`vscode.fritz.box`)
      entryPoints:
        - "web"
      middlewares:
        - ondemand@docker
      service: "code-server"
```
