### ISSUE TITLE
workload shuts down while in use

### ISSUE THREAD

**Issue by VamPikmin** [acouvreur/sablier#391]
First of all, thank you so much for creating sablier

I've been trying to set it up but have come across an issue I can't seem to figure out on my own.

Setup:
sablier plugin enabled in traefik,toml
[experimental.plugins.sablier]
  moduleName = "github.com/acouvreur/sablier"
  version = "v1.8.0-beta.19

traefik_dynamic.toml
```toml
[http]
  [http.middlewares]
    [http.middlewares.sablier]
      [http.middlewares.sablier.plugin]
        [http.middlewares.sablier.plugin.sablier]
          group = "default"
          names = "filebrowser"
          sablierUrl = "http://sablier:10000"
          sessionDuration = "1m"

          [http.middlewares.sablier.plugin.sablier.dynamic]
            displayName = "Test message"
            refreshFrequency = "5s"
            showDetails = "true"
            theme = "shuffle"

[http.routers.filebrowser]
  rule = "Host(`filebrowser.domain`)"
  entrypoints = ["websecure"]
  middlewares = ["sablier"]
  service = "filebrowser"
  [http.services.filebrowser.loadBalancer]
  [[http.services.filebrowser.loadBalancer.servers]]
    url = "http://filebrowser"
  [http.routers.filebrowser.tls]
    certResolver = "lets-encrypt"
```

The container starts up fine with the "Test message" I am able to login to the webpage but after 1 min it shuts down even when in use.

I am actively browsing the web page and downloading a file.

I have also tried snapdrop docker, it appears to be also turning off after 1min

**Context**
 - Sablier version: 1.7.0
 - Provider: docker 27.2.0
 - Reverse proxy: traefik v3.1.2
 - Sablier running inside a container? Yes

**Expected behavior**
I expected sablier not to shut the workload off because I'm actively downloading a file or browsing

Thank you for your time
